# -*- coding: utf-8 -*-
# Konten buku — Hama, Penyakit & Masalah Hara Padi di Lahan Tadah Hujan Kalimantan Barat.
# Diadaptasi dari versi pasang surut ke ekosistem tadah hujan (tanah mineral masam / ultisol-podzolik,
# rawan kekeringan) khas Sekadau, Sintang, dan sekitarnya.

HAMA=[
{"no":1,"nama":"Penggerek Batang Padi","latin":"Scirpophaga incertulas, S. innotata, Chilo suppressalis, Sesamia inferens","photo":"penggerek.png","cap":"Gejala sundep (anakan mati, mudah dicabut) akibat penggerek batang.","suggest":None,
 "gejala":"Dua gejala utama. SUNDEP: pada fase vegetatif, pucuk/anakan muda mati, layu, mengering, dan mudah dicabut. BELUK: pada fase generatif, malai muncul putih/hampa, kering, dan mudah dicabut; pada pangkalnya terlihat bekas gerekan larva.",
 "pembeda":"Anakan/malai yang mati mudah dicabut dan pada pangkal batang ada lubang gerekan serta kotoran larva — berbeda dari kresek HDB (daun menggulung, tidak ada lubang) dan dari kerusakan orong-orong (batang terpotong dari luar di pangkal, dekat permukaan tanah).",
 "penyebab":"Larva (ulat) lima spesies ngengat penggerek yang menggerek dan memakan bagian dalam batang sehingga aliran hara/asimilat terputus.",
 "kondisi":"Cuaca panas dengan air tergenang; penanaman tidak serempak; sisa singgang/tunggul jerami sebagai sumber larva. Di lahan tadah hujan, populasi meningkat bila tanam tidak seragam sehingga selalu tersedia tanaman inang.",
 "dampak":"Kehilangan hasil pada fase vegetatif relatif kecil (tanaman membentuk anakan baru), tetapi serangan pada fase generatif (beluk) langsung menurunkan jumlah gabah berisi.",
 "identifikasi":"Amati kelompok telur di daun persemaian, kehadiran ngengat pada malam hari (perangkap lampu), serta anakan/malai mati yang mudah dicabut. Ambang: kerusakan >5 rumpun/petak, atau tangkap ngengat 4 hari setelah muncul ngengat.",
 "pht":["Tanam serempak dalam satu hamparan dan olah tanah/benamkan singgang untuk memutus daur hidup.",
  "Ambil dan musnahkan kelompok telur di persemaian; pasang perangkap feromon seks atau lampu untuk menangkap ngengat massal.",
  "Lestarikan musuh alami parasitoid telur: Trichogramma japonicum, Telenomus rowani, Tetrastichus schoenobii.",
  "Bersihkan singgang dan gulma inang di sekitar petak; atur pola tanam antar-hamparan agar tidak selalu ada tanaman muda.",
  "Bila ambang terlampaui: insektisida berbahan aktif klorantraniliprol, spinetoram, dimehipo, atau karbofuran 20 kg/ha (fase vegetatif); rotasi bahan aktif."],
 "tip":"Cabut uji beberapa anakan mati — bila putus mudah dan berlubang, itu penggerek; bila pangkal tergigit rata dari luar, curigai orong-orong."},
{"no":2,"nama":"Wereng Batang Coklat (WBC)","latin":"Nilaparvata lugens","photo":"wbc.png","cap":"Koloni wereng batang coklat berkerumun pada pangkal batang padi.","suggest":None,
 "gejala":"Tanaman menguning dari daun tua lalu mengering cepat seperti terbakar (hopperburn), sering melingkar/berkelompok dalam hamparan. Wereng berkerumun di pangkal batang dekat permukaan air.",
 "pembeda":"Menguning 'terbakar' berkelompok disertai kerumunan serangga coklat di pangkal batang — berbeda dari keracunan besi (daun bawah bronzing merata satu hamparan tanpa serangga) dan tungro (daun jingga dari ujung, tanaman kerdil).",
 "penyebab":"Nimfa dan imago WBC mengisap cairan pangkal batang; juga menularkan virus kerdil rumput (grassy stunt) dan kerdil hampa (ragged stunt).",
 "kondisi":"Lembap dan panas, pemupukan N berlebihan, tanam varietas rentan, jarak tanam rapat, dan penggunaan insektisida keliru yang membunuh musuh alami (resurgensi).",
 "dampak":"Puso pada populasi tinggi; kehilangan hasil luas dan hampir tiap musim; penularan penyakit virus kerdil.",
 "identifikasi":"Buka rumpun, ketuk pangkal batang di atas air — wereng jatuh mengapung. Ambang: rata-rata 10 ekor/rumpun (<40 HST) atau 20 ekor/rumpun (>40 HST); atau >3 ekor/rumpun bila ada gejala.",
 "pht":["Tanam varietas tahan WBC (mis. Inpari 33) dan lakukan tanam serempak; beri jeda bera/pergiliran tanaman non-padi.",
  "Pemupukan N berimbang (pakai Bagan Warna Daun) dan jarak tanam tidak terlalu rapat (jajar legowo).",
  "Lestarikan musuh alami: laba-laba Lycosa pseudoannulata, kepik Cyrtorhinus lividipennis, kumbang Paederus; jamur Beauveria bassiana/Metarhizium.",
  "Keringkan petak sebelum aplikasi; semprot mengenai pangkal batang saat embun hilang (pukul 08.00-11.00).",
  "Bila ambang terlampaui: triflumezopyrim, pimetrozin, atau dinotefuran (rotasi); hindari bahan aktif yang memicu resurgensi."],
 "tip":"Jangan menyemprot 'terjadwal'. Semprot hanya bila hitungan per rumpun melampaui ambang, agar musuh alami tetap bekerja dan wereng tidak resisten."},
{"no":3,"nama":"Wereng Hijau","latin":"Nephotettix virescens","photo":None,"cap":None,"suggest":"Imago wereng hijau (hijau, ujung sayap kehitaman) di helai daun padi muda, close-up.",
 "gejala":"Sendiri jarang menimbulkan kerusakan mencolok, tetapi menghisap daun tanaman muda. Perannya paling penting sebagai penular (vektor) penyakit tungro — gejala tungro (daun jingga, kerdil) menyusul.",
 "pembeda":"Serangga hijau kecil (2,5-3 mm) berujung sayap kehitaman, lincah meloncat; kehadirannya pada pertanaman muda menjadi tanda bahaya tungro, berbeda dari WBC yang coklat dan berkerumun di pangkal batang.",
 "penyebab":"Nephotettix virescens (terutama) mengisap cairan daun dan memindahkan Rice Tungro Bacilliform Virus (RTBV) + Rice Tungro Spherical Virus (RTSV).",
 "kondisi":"Pertanaman tidak serempak (selalu ada tanaman muda), sumber inokulum tungro tersedia, dan pemupukan N berlebih yang membuat tanaman lunak/menarik wereng.",
 "dampak":"Kerusakan langsung ringan; kerugian utama melalui penularan tungro yang bisa menurunkan hasil 20-90% tergantung umur saat terinfeksi.",
 "identifikasi":"Gunakan perangkap lampu atau ayunan jaring di persemaian dan pertanaman muda; pantau puncak populasi 1,5-2 bulan setelah puncak curah hujan.",
 "pht":["Tanam serempak dan atur waktu tanam agar tanaman berumur >45 HST saat puncak populasi wereng hijau.",
  "Tanam varietas tahan tungro/wereng hijau; cabut dan benamkan tanaman bergejala tungro (eradikasi sumber inokulum).",
  "Pemupukan N sesuai anjuran (BWD); jangan keringkan sawah total agar wereng tidak aktif berpindah.",
  "Lestarikan musuh alami (laba-laba, kepik Cyrtorhinus); gunakan insektisida hanya bila populasi tinggi pada fase rentan."],
 "tip":"Wereng hijau adalah 'alarm tungro'. Bila ditemukan banyak di sawah muda yang bertetangga dengan petak bergejala jingga, segera eradikasi tanaman sakit."},
{"no":4,"nama":"Tikus Sawah","latin":"Rattus argentiventer","photo":"tikus_tbs.png","cap":"Sistem bubu perangkap (TBS/LTBS) dengan pagar plastik dan tanaman perangkap.","suggest":None,
 "gejala":"Tanaman terpotong rapi menyerong pada batang, sering dari tengah petak meluas ke tepi; potongan anakan/malai berserakan. Ada jejak jalur, kotoran, dan lubang aktif di pematang/tanggul.",
 "pembeda":"Potongan batang bersudut khas gigitan dan kerusakan berpola (dari dalam ke luar petak) — berbeda dari orong-orong (potong di pangkal dekat tanah) dan penggerek (anakan mati berlubang, tidak terpotong lepas).",
 "penyebab":"Tikus sawah yang berkembang biak cepat; habitat utama di tanggul irigasi, semak, dan pematang besar.",
 "kondisi":"Banyak semak dan lahan bera di sekitar sawah, pematang lebar/tinggi sebagai sarang, tanam tidak serempak yang menyediakan pakan generatif terus-menerus. Umum di petak tadah hujan yang berbatasan semak, kebun, dan hutan.",
 "dampak":"Salah satu penyebab kerusakan terbesar; menyerang sejak persemaian sampai menjelang panen, dapat menyebabkan puso setempat.",
 "identifikasi":"Hitung rumpun rusak dan lubang aktif. Ambang tindakan: >10% rumpun rusak atau ditemukan tanda serangan aktif; pengendalian dimulai dini (pra-tanam).",
 "pht":["Gerakan bersama (berkelompok, hamparan) sejak pra-tanam: sanitasi semak, gropyokan, penggenangan lubang, dan perataan pematang (<30 cm).",
  "Pasang Trap Barrier System (TBS)/Linear TBS dengan pagar plastik dan bubu perangkap; efektif untuk migrasi dari habitat semak/kebun.",
  "Fumigasi/pengemposan belerang pada sarang aktif terutama saat fase generatif; tutup lubang dengan lumpur.",
  "Lindungi/manfaatkan predator alami: burung hantu (Tyto alba) dengan rumah burung (rubuha), ular sawah, kucing.",
  "Umpan rodentisida (antikoagulan) dicampur gabah hanya bila populasi tinggi, diletakkan di jalur lintasan tikus."],
 "tip":"Tikus dikendalikan sebelum, bukan sesudah, populasi meledak. Pra-tanam serentak satu hamparan jauh lebih murah daripada mengumpan saat generatif."},
{"no":5,"nama":"Keong Mas","latin":"Pomacea canaliculata","photo":"keong.png","cap":"Kelompok telur keong mas berwarna merah muda menempel pada batang di atas air.","suggest":None,
 "gejala":"Bibit muda habis dimakan; daun dan batang muda terpotong terlihat mengambang. Kelompok telur merah muda menempel pada batang, ajir, dan tepi petak di atas permukaan air.",
 "pembeda":"Kerusakan pada 10-21 hari pertama setelah tanam disertai telur merah muda dan keong bercangkang kuning keemasan — sangat khas, tidak mirip hama lain.",
 "penyebab":"Keong mas memarut dan memakan jaringan tanaman muda; herbivora rakus (polifag).",
 "kondisi":"Air menggenang/diam, lahan tidak rata, dan saluran tidak terkendali. Petak tadah hujan dataran rendah yang tergenang air hujan di awal musim serta saluran/rawa di sekitarnya menjadi tempat keong berkembang.",
 "dampak":"Bibit hilang sehingga tanaman jarang/rumpang; pada serangan parah harus tanam ulang. Kritis pada 10 HST (tanam pindah) dan sampai 21 HST (tabela).",
 "identifikasi":"Amati keong dan telur merah muda saat pengolahan lahan dan awal tanam; pantau titik-titik air tergenang. Ambang: >3 ekor/rumpun atau >5% tanaman terserang.",
 "pht":["Ratakan lahan dan kelola air: buat caren/saluran kecil agar keong terkumpul, lalu keringkan petak sampai fase anakan.",
  "Pungut keong dan hancurkan telur pagi/sore; pasang ajir bambu sebagai tempat bertelur agar mudah diambil.",
  "Pasang saringan kawat/bambu di pintu masuk-keluar air untuk mencegah keong masuk.",
  "Gunakan umpan daun menarik (pepaya, talas, pisang) di tepi petak; gembalakan itik pada persiapan lahan/akhir.",
  "Bila perlu: moluskisida saponin/rerak (nabati) atau berbahan aktif niklosamida; pilih yang berdaya racun rendah bagi ikan."],
 "tip":"Buat parit kecil keliling petak — keong akan berkumpul di parit saat air surut sehingga sekali jalan bisa dipungut banyak."},
{"no":6,"nama":"Walang Sangit","latin":"Leptocorisa oratorius","photo":"walangsangit.png","cap":"Walang sangit dewasa (langsing, hijau kecoklatan) pada malai padi.","suggest":None,
 "gejala":"Bulir pada fase masak susu terhisap sehingga gabah menjadi hampa, berbintik coklat, beras berubah warna dan mengapur. Tercium bau menyengat khas saat berada di pertanaman.",
 "pembeda":"Bau menyengat + serangga langsing hijau kecoklatan pada malai; gabah hampa/bernoda pada fase pengisian — berbeda dari beluk penggerek (seluruh malai putih dan mudah dicabut).",
 "penyebab":"Nimfa dan imago walang sangit mengisap cairan bulir yang sedang mengisi.",
 "kondisi":"Hampir selalu ada tiap musim; meningkat bila banyak gulma berbunga di sekitar sawah dan tanam tidak seragam. Berlimpah pada pertanaman berbunga yang tidak serempak, umum di lahan tadah hujan yang berdekatan semak.",
 "dampak":"Menurunkan bobot dan mutu gabah (hampa, mengapur, berubah warna) pada fase berbunga sampai matang susu.",
 "identifikasi":"Ayun jaring pada pagi/sore saat fase berbunga-masak susu; hitung ekor per ayunan/rumpun.",
 "pht":["Kendalikan gulma di sawah dan sekitarnya; tanam dan panen serempak agar fase pengisian tidak berkepanjangan.",
  "Pupuk merata agar tanaman masak seragam sehingga masa rentan singkat.",
  "Umpan bangkai (ikan/keong busuk, kotoran ayam) untuk mengumpulkan lalu memusnahkan; tangkap dengan jaring sebelum pembungaan.",
  "Bila ambang terlampaui: insektisida kontak berbahan aktif BPMC, MIPC, propoksur, atau fipronil, disemprot pagi/sore."],
 "tip":"Pasang umpan bangkai di beberapa titik tepi petak menjelang pembungaan — walang sangit berkumpul di umpan dan lebih mudah dikendalikan."},
{"no":7,"nama":"Orong-orong (Anjing Tanah)","latin":"Gryllotalpa orientalis","photo":"orongorong.png","cap":"Orong-orong (anjing tanah) dan pangkal tanaman yang terpotong.","suggest":None,
 "gejala":"Tanaman terpotong pada pangkal batang dekat/di bawah permukaan tanah; akar muda dan pangkal rusak. Sering muncul saat lahan tidak tergenang.",
 "pembeda":"Potongan tepat di pangkal batang dekat tanah dan kerusakan akar bawah tanah — mudah dikira sundep penggerek, tetapi orong-orong memotong dari luar dan meninggalkan liang di tanah.",
 "penyebab":"Orong-orong (jangkrik penggali) yang aktif di tanah lembap tanpa genangan.",
 "kondisi":"Sawah tadah hujan dan lahan kering yang tanahnya gembur/lembap tanpa genangan — kondisi yang sering terjadi di lahan tadah hujan sehingga orong-orong cukup umum. Penggenangan membuat orong-orong pindah ke pematang.",
 "dampak":"Merusak tanaman pada semua fase, terutama merusak bibit dan pangkal tanaman muda sehingga rumpang.",
 "identifikasi":"Amati liang di tanah dan tanaman rebah terpotong di pangkal, terutama di petak yang mengering.",
 "pht":["Olah tanah untuk membunuh telur dan nimfa; genangi sawah 3-4 hari (bila air tersedia) untuk menekan telur di tanah.",
  "Ambil orong-orong secara mekanis saat pengolahan tanah (yang muncul berenang).",
  "Gunakan umpan sekam dicampur insektisida di titik serangan; bila perlu bahan aktif karbofuran atau fipronil."],
 "tip":"Jaga genangan tipis pada fase awal bila air tersedia — orong-orong tidak menyukai petak yang tergenang dan akan pindah ke pematang."},
{"no":8,"nama":"Hama Putih Palsu (Pelipat Daun)","latin":"Cnaphalocrocis medinalis","photo":None,"cap":None,"suggest":"Daun padi tergulung/terlipat memanjang dengan garis putih transparan; larva di dalam gulungan.",
 "gejala":"Daun terlipat/tergulung memanjang; di dalam gulungan ada larva yang memakan jaringan hijau sehingga terbentuk garis-garis putih transparan sepanjang 15-20 cm.",
 "pembeda":"Daun tergulung dengan 'jendela' putih transparan (epidermis tersisa) — berbeda dari hama putih (Nymphula) yang membuat garis putih tanpa menggulung rapat, dan dari kresek HDB (menggulung layu tanpa jendela putih).",
 "penyebab":"Larva ngengat pelipat daun yang melipat daun sebagai tempat berlindung sambil mengerok jaringan daun.",
 "kondisi":"Kelembapan tinggi, pemupukan N berlebih, dan tajuk rapat pada fase vegetatif-sebelum berbunga.",
 "dampak":"Umumnya ringan; menjadi berarti bila kerusakan daun mencapai ~50% atau daun bendera ikut rusak pada fase pengisian.",
 "identifikasi":"Hitung persentase daun terlipat/terserang per rumpun contoh; perhatikan daun bendera. Kendalikan bila kerusakan tinggi/mengancam daun bendera.",
 "pht":["Pemupukan N berimbang dan jarak tanam tidak terlalu rapat agar tajuk tidak lembap.",
  "Lestarikan parasitoid larva dan laba-laba predator; hindari penyemprotan dini yang tidak perlu.",
  "Buang/rendam daun terlipat pada serangan terbatas; insektisida hanya bila kerusakan daun tinggi atau mengancam daun bendera."],
 "tip":"Lindungi daun bendera. Kerusakan daun bawah jarang menurunkan hasil; yang menentukan adalah daun bendera dan tiga daun teratas."},
{"no":9,"nama":"Ganjur","latin":"Orseolia oryzae","photo":None,"cap":None,"suggest":"Anakan padi membentuk 'pentil bawang'/tabung perak (silver shoot) akibat ganjur.",
 "gejala":"Anakan yang terserang membentuk tabung menyerupai daun bawang (silver shoot / 'pentil bawang') berwarna keputihan; anakan tidak menghasilkan malai.",
 "pembeda":"Pembentukan tabung/pentil khas pada pucuk anakan — sangat berbeda dari gejala penggerek (anakan mati) maupun penyakit; tabung ini adalah puru akibat larva ganjur.",
 "penyebab":"Larva lalat ganjur yang merangsang pucuk anakan membentuk puru berbentuk tabung sehingga titik tumbuh gagal bermalai.",
 "kondisi":"Kelembapan tinggi, banyak embun, cuaca mendung berkepanjangan, tanam tidak serempak, dan pertanaman padi terus-menerus. Muncul terutama pada awal musim hujan yang lembap.",
 "dampak":"Anakan terserang tidak produktif; bila banyak, jumlah malai per rumpun turun sehingga hasil berkurang.",
 "identifikasi":"Hitung jumlah anakan bertabung 'pentil bawang' per rumpun pada fase anakan; pantau pada musim/lokasi berembun tinggi.",
 "pht":["Tanam serempak dan gunakan varietas tahan ganjur bila tersedia; olah/benamkan singgang sumber serangga.",
  "Pemupukan N berimbang; hindari kelebihan N yang memicu anakan lunak.",
  "Lestarikan parasitoid ganjur (Platygaster, Neanastatus); insektisida sistemik hanya bila serangan tinggi pada fase anakan."],
 "tip":"Kenali 'pentil bawang' sejak fase anakan — anakan bertabung tidak akan bermalai, jadi keputusan tindakan diambil sebelum fase generatif."},
{"no":10,"nama":"Belalang & Ulat Grayak","latin":"Oxya spp., Spodoptera mauritia","photo":None,"cap":None,"suggest":"Daun padi terkoyak/berlubang dari tepi oleh belalang; atau ulat grayak berkelompok memakan daun pada malam hari.",
 "gejala":"Daun terkoyak, berlubang, atau habis dimakan dari tepi/ujung; pada serangan ulat grayak (armyworm) daun ludes berkelompok, sering pada malam hari, dan larva bersembunyi di pangkal/tanah pada siang hari.",
 "pembeda":"Daun robek/berlubang dengan sisa gigitan kasar dan ada serangga pemakan daun (belalang meloncat, ulat grayak berbaris) — berbeda dari hama putih palsu (daun tergulung dengan jendela putih) dan defisiensi hara (tanpa bekas gigitan).",
 "penyebab":"Belalang (Oxya spp.) dan larva ngengat ulat grayak (Spodoptera mauritia) yang memakan jaringan daun.",
 "kondisi":"Umum pada lahan tadah hujan/kering yang berbatasan gulma, semak, dan lahan bera; ulat grayak sering meledak setelah kekeringan diikuti hujan pertama. Populasi naik pada persemaian dan tanaman muda.",
 "dampak":"Merusak daun pada persemaian sampai fase vegetatif; pada ledakan ulat grayak dapat menggunduli persemaian dalam semalam.",
 "identifikasi":"Amati daun terkoyak dan kotoran ulat pada pagi hari; periksa pangkal tanaman/tanah untuk larva yang bersembunyi. Waspadai persemaian setelah hujan pertama musim.",
 "pht":["Sanitasi gulma dan sisa tanaman di sekitar persemaian; olah tanah untuk mengurangi pupa di tanah.",
  "Pantau persemaian dan tanaman muda; kumpulkan larva/belalang secara manual dan gembalakan itik/ayam pada serangan awal.",
  "Lestarikan musuh alami (laba-laba, kepik, burung, parasitoid); pasang perangkap lampu untuk ngengat ulat grayak.",
  "Bila serangan tinggi terutama di persemaian: insektisida berbahan aktif klorantraniliprol, emamektin benzoat, atau sesuai anjuran, disemprot sore hari."],
 "tip":"Ulat grayak menyerang malam dan sembunyi siang hari — periksa pangkal tanaman dan tanah pada pagi buta untuk memastikan penyebab daun habis."},
{"no":11,"nama":"Burung Pipit","latin":"Lonchura spp.","photo":None,"cap":None,"suggest":"Kawanan burung pipit menyerang malai padi menjelang panen; bulir kosong/rontok.",
 "gejala":"Bulir dimakan sehingga gabah kosong/hampa dan malai rusak; serangan bergerombol pada pagi (06.00-10.00) dan sore (15.00-18.00) menjelang panen.",
 "pembeda":"Kerusakan pada malai matang menjelang panen oleh kawanan burung — berbeda dari walang sangit (gabah bernoda pada masak susu, ada bau) dan beluk penggerek.",
 "penyebab":"Burung pipit pemakan biji yang menyerang saat pengisian-pematangan bulir (umumnya 70-80 HST).",
 "kondisi":"Petak dekat semak/pohon tempat bertengger, tanam tidak serempak (ada petak matang lebih dulu menjadi sasaran), dan hamparan kecil terisolasi. Umum di lahan tadah hujan yang berbatasan kebun dan hutan.",
 "dampak":"Kehilangan hasil bisa besar (dilaporkan hingga 50%) pada petak yang matang lebih awal atau terisolasi.",
 "identifikasi":"Amati kehadiran kawanan pada jam rawan dan malai rusak/rontok di tepi petak yang berbatasan semak.",
 "pht":["Tanam serempak satu hamparan agar tekanan burung terbagi rata (tidak terfokus pada satu petak matang).",
  "Pasang jaring pelindung, tali berumbai/kaleng bunyi, dan orang-orangan; lakukan pengusiran pada jam rawan.",
  "Kelola vegetasi bertengger di sekitar sawah; panen tepat waktu (80-85% bulir menguning) agar masa rawan singkat."],
 "tip":"Petak yang matang sendirian jadi sasaran empuk. Keseragaman tanam satu hamparan adalah 'pengendalian burung' yang paling murah."},
]

PENYAKIT=[
{"no":12,"nama":"Hawar Daun Bakteri (HDB / Kresek)","latin":"Xanthomonas oryzae pv. oryzae","photo":"hdb.png","cap":"Hawar pada tepi daun: bercak abu-abu kekuningan meluas dari tepi/ujung daun.","suggest":None,
 "gejala":"Dua bentuk. KRESEK (tanaman muda <30 hari): daun hijau kelabu, melipat, menggulung, layu, dan mati — mirip tanaman terserang penggerek. HAWAR (anakan-pemasakan): bercak abu-abu kekuningan dari tepi/ujung daun meluas membentuk hawar dan daun mengering.",
 "pembeda":"Pada pagi hari yang lembap terlihat butiran/eksudat bakteri kuning keemasan pada tepi daun bergejala (bisa diuji dengan menempel/menggores) — pembeda kunci dari blas (bercak belah ketupat) dan hawar daun jingga (garis jingga).",
 "penyebab":"Bakteri Xanthomonas oryzae pv. oryzae; menyebar lewat angin, gesekan antar-daun, air hujan/irigasi, dan luka pada bibit.",
 "kondisi":"Musim hujan atau kemarau basah, lahan selalu tergenang, pemupukan N tinggi (>250 kg Urea/ha), jarak tanam rapat, dan ujung bibit terpotong saat tanam. Serangan sering meningkat pada awal musim hujan yang basah di lahan tadah hujan.",
 "dampak":"Menurunkan hasil hingga ~30%; kresek pada tanaman muda dapat mematikan rumpun. Merupakan penyakit sasaran utama seleksi varietas PM-AAS.",
 "identifikasi":"Cari eksudat bakteri kuning pada tepi daun pagi hari; amati pola hawar dari tepi/ujung. Ambang tindakan preventif: kelembapan tinggi + varietas rentan; semprot bila intensitas >5% daun / >20% pada varietas rentan.",
 "pht":["Tanam varietas tahan HDB (mis. Inpari 32 HDB, Inpari 42 GSR, Mantap) — komponen kunci PM-AAS untuk lahan tadah hujan.",
  "Jangan memotong ujung bibit saat tanam; jarak tanam jajar legowo agar tajuk tidak lembap.",
  "Pengairan berselang/AWD bila air tersedia (hindari genangan terus-menerus); pemupukan N berimbang (BWD), tambah silika untuk memperkuat jaringan.",
  "Sanitasi jerami dan gulma inang; agens hayati Pseudomonas fluorescens.",
  "Bila intensitas tinggi: bakterisida berbahan aktif tembaga hidroksida/tembaga oksiklorida sesuai anjuran (bukan fungisida)."],
 "tip":"Kresek sering dikira serangan penggerek. Bedakan: kresek membuat daun menggulung-layu tanpa lubang gerekan; penggerek membuat anakan mati yang mudah dicabut dan berlubang."},
{"no":13,"nama":"Blas (Blast)","latin":"Pyricularia oryzae (Magnaporthe oryzae)","photo":"blas_daun.png","cap":"Blas daun: bercak belah ketupat, pusat abu-abu/putih, tepi coklat.","suggest":None,
 "gejala":"BLAS DAUN: bercak belah ketupat (mata), ujung meruncing, pusat putih/abu-abu, tepi coklat. BLAS LEHER: pangkal leher malai membusuk coklat kehitaman sehingga malai patah/hampa (patah leher).",
 "pembeda":"Bercak belah ketupat bermata pada daun sangat khas blas — berbeda dari bercak coklat (bercak oval/bulat sebesar biji wijen, merata) dan HDB (hawar dari tepi daun).",
 "penyebab":"Cendawan Pyricularia oryzae (tahap sempurna Magnaporthe oryzae); menular lewat spora udara dan benih.",
 "kondisi":"Kelembapan/embun tinggi, N berlebih, tanam rapat (tajuk lembap), suhu sejuk-lembap saat berbunga. Padi tadah hujan/gogo dan tanam rapat paling berisiko — blas adalah penyakit utama di lahan tadah hujan Kalbar.",
 "dampak":"Kehilangan hasil besar (50-90%); blas leher sangat merugikan karena langsung mematikan pengisian malai.",
 "identifikasi":"Cari bercak mata belah ketupat pada daun sejak fase anakan; periksa leher malai saat berbunga-pengisian. Ambang: >5-10% daun terserang atau ditemukan gejala pada malai.",
 "pht":["Tanam varietas tahan blas dan bergilir antar-musim (ras cendawan cepat berubah); untuk tadah hujan utamakan varietas tahan blas seperti Inpari 39 Tadah Hujan (tahan 4 ras blas).",
  "Perlakuan benih dengan fungisida sistemik (mis. trisiklazol) karena blas terbawa benih.",
  "Pupuk N sesuai anjuran (dosis N tinggi menaikkan serangan); tambahkan silika untuk memperkuat epidermis daun.",
  "Atur waktu tanam agar pembungaan tidak bertepatan dengan periode banyak embun; jarak tanam tidak terlalu rapat.",
  "Bila perlu: fungisida berbahan aktif trisiklazol, isoprotiolan, kasugamisin, atau azoksistrobin — semprot preventif saat awal berbunga (lindungi leher malai)."],
 "tip":"Semprot pelindung blas leher dilakukan menjelang keluar malai, bukan setelah leher membusuk — sekali leher patah, kerusakan tidak dapat dipulihkan."},
{"no":14,"nama":"Tungro","latin":"RTBV + RTSV (ditularkan wereng hijau)","photo":"tungro.png","cap":"Gejala tungro: daun menguning-jingga dari ujung, tanaman kerdil.","suggest":None,
 "gejala":"Daun berubah kuning sampai jingga dimulai dari ujung meluas ke pangkal; tanaman kerdil, anakan sedikit, malai pendek, dan banyak gabah hampa.",
 "pembeda":"Perubahan warna jingga dari ujung daun + kekerdilan pada rumpun berkelompok (fokus) — berbeda dari keracunan besi (bronzing coklat daun bawah, satu hamparan merata) dan defisiensi N (menguning pucat merata tanpa kerdil mencolok).",
 "penyebab":"Infeksi ganda Rice Tungro Bacilliform Virus (RTBV) dan Rice Tungro Spherical Virus (RTSV), ditularkan wereng hijau (Nephotettix virescens).",
 "kondisi":"Tanam tidak serempak (sumber inokulum + tanaman muda selalu ada), populasi wereng hijau tinggi, dan varietas peka. Makin muda tanaman terinfeksi makin besar kerugian.",
 "dampak":"Kehilangan hasil 20-90% tergantung umur saat terinfeksi; tanaman sakit tidak dapat disembuhkan.",
 "identifikasi":"Amati kelompok tanaman kerdil menguning-jingga (pola fokus/menyebar dari satu titik) dan kehadiran wereng hijau; konfirmasi dengan pola warna dari ujung daun.",
 "pht":["Tanam serempak satu hamparan dan atur waktu tanam agar tanaman >45 HST saat puncak wereng hijau.",
  "Tanam varietas tahan tungro; segera eradikasi (cabut + benamkan) tanaman sakit untuk menghilangkan sumber inokulum.",
  "Pemupukan N sesuai anjuran (BWD); jangan keringkan sawah total agar wereng tidak aktif menyebar.",
  "Kendalikan vektor wereng hijau berdasarkan pemantauan (lihat entri Wereng Hijau), utamakan musuh alami."],
 "tip":"Tungro dikelola dengan 'putus rantai': serempak tanam + eradikasi tanaman sakit + kendalikan wereng hijau. Menyemprot tanaman yang sudah sakit tidak menyembuhkan."},
{"no":15,"nama":"Bercak Coklat","latin":"Bipolaris oryzae (Helminthosporium oryzae)","photo":"bercak_coklat.png","cap":"Bercak coklat oval sebesar biji wijen tersebar merata pada daun.","suggest":None,
 "gejala":"Bercak oval sampai bulat sebesar biji wijen, coklat dengan pusat kuning pucat/putih kotor, tersebar merata pada daun; juga pada pelepah dan kulit gabah (gabah bernoda).",
 "pembeda":"Bercak kecil oval 'biji wijen' yang banyak dan merata — berbeda dari blas (belah ketupat bermata) dan HDB (hawar tepi daun). Sering menandakan lahan miskin hara (khususnya K) atau kekeringan.",
 "penyebab":"Cendawan Bipolaris oryzae; patogen terbawa benih (seed borne).",
 "kondisi":"Tanah kurang subur/kekurangan hara terutama Kalium (K) dan cekaman kekeringan — sangat relevan di lahan tadah hujan yang miskin hara (N, P, K rendah). Berkembang cepat pada tanaman lemah.",
 "dampak":"Mematikan tanaman muda, menurunkan mutu dan bobot gabah; indikator lahan bermasalah hara/air.",
 "identifikasi":"Cari bercak 'biji wijen' merata pada daun dan noda pada gabah; kaitkan dengan status hara/kekeringan petak.",
 "pht":["Perbaiki kesuburan: pemupukan berimbang terutama Kalium; ameliorasi bahan organik untuk lahan tadah hujan masam.",
  "Gunakan benih sehat/perlakuan benih; tanam varietas tahan (mis. Ciherang).",
  "Jaga ketersediaan air pada fase kritis; jarak tanam jajar legowo (tidak rapat).",
  "Bila perlu: fungisida berbahan aktif mankozeb, azoksistrobin, difenokonazol, atau tebukonazol."],
 "tip":"Bercak coklat yang meluas sering 'gejala lapar hara' atau tanaman stres kering. Sebelum menyemprot, perbaiki Kalium, bahan organik, dan ketersediaan air."},
{"no":16,"nama":"Hawar Pelepah Daun","latin":"Rhizoctonia solani","photo":"hawar_pelepah.png","cap":"Bercak oval kelabu-hijau pada pelepah dekat permukaan air (hawar pelepah).","suggest":None,
 "gejala":"Bercak pada pelepah dekat permukaan air, oval/elips 1-3 cm, pusat putih keabu-abuan bertepi coklat; meluas ke atas sampai daun bendera. Tampak sklerotia coklat kecil mudah lepas dan benang miselia putih.",
 "pembeda":"Bercak mulai dari pelepah dekat air lalu naik + ada sklerotia coklat seperti butiran — khas hawar pelepah; perlu membuka kanopi untuk melihatnya.",
 "penyebab":"Cendawan Rhizoctonia solani; bertahan sebagai sklerotia di tanah/sisa tanaman.",
 "kondisi":"Tanam rapat, N berlebih, kanopi rapat lembap, dan pertanaman terus-menerus. Umum dari dataran rendah sampai tinggi.",
 "dampak":"Tanaman mudah rebah, gabah tidak berisi penuh/hampa; kehilangan hasil hingga ~30%, terutama bila menyerang awal.",
 "identifikasi":"Buka kanopi dan periksa pelepah dekat garis air untuk bercak oval bertepi coklat dan sklerotia; pantau sejak fase anakan.",
 "pht":["Jarak tanam tidak terlalu rapat (jajar legowo) dan pemupukan N berimbang untuk mengurangi kelembapan tajuk.",
  "Pengairan berselang/AWD bila air tersedia; sanitasi sisa tanaman dan gulma inang untuk mengurangi sklerotia.",
  "Agens hayati Trichoderma; bila perlu fungisida berbahan aktif validamisin, difenokonazol, mankozeb, atau benomil."],
 "tip":"Penyakit ini 'tersembunyi' di bawah kanopi. Pada varietas anakan lebat, buka rumpun rutin dekat permukaan air untuk deteksi dini."},
{"no":17,"nama":"Hawar Daun Jingga (Bacterial Red Stripe)","latin":"Diduga Pseudomonas sp. / Bacillus sp.","photo":"hdj.png","cap":"Garis/bercak jingga pada helai daun (hawar daun jingga).","suggest":None,
 "gejala":"Diawali bercak kecil berwarna jingga di helai daun (bisa di mana saja), lalu berkembang menjadi hawar menyerupai HDB. Muncul terutama saat fase generatif.",
 "pembeda":"Warna jingga pada bercak/garis daun yang khas — berbeda dari HDB (bercak abu-abu kekuningan dari tepi) dan tungro (jingga menyeluruh + kerdil).",
 "penyebab":"Diduga bakteri Pseudomonas sp. dan Bacillus sp. (bacterial red stripe).",
 "kondisi":"Dataran rendah (<100 m dpl), pertanaman selalu tergenang, N berlebih, dan jarak tanam rapat; sering pada fase generatif.",
 "dampak":"Meningkatkan gabah hampa serupa kerugian akibat HDB.",
 "identifikasi":"Cari garis/bercak jingga pada daun fase generatif; bedakan dari HDB lewat warna jingga dan dari tungro lewat tidak adanya kekerdilan menyeluruh.",
 "pht":["Pemupukan berimbang (kurangi kelebihan N) dan jarak tanam tidak terlalu rapat.",
  "Pengairan berselang; hindari genangan terus-menerus.",
  "Sanitasi dan gunakan benih/varietas sehat; tindakan kimia jarang diperlukan bila kultur teknis diperbaiki."],
 "tip":"Perbaikan N dan pengelolaan air biasanya cukup meredam hawar daun jingga — jarang perlu bakterisida bila kultur teknis benar."},
]

HARA=[
{"no":18,"nama":"Kemasaman Tanah & Keracunan Aluminium (Al)","latin":"Al3+ berlebih, pH < 4,5","photo":None,"cap":None,"suggest":"Akar padi pendek, tumpul, dan menghitam; tanaman kerdil dan tumbuh tidak merata pada petak bertanah merah-kuning masam.",
 "gejala":"Akar terhambat, pendek, tumpul, dan berwarna gelap sehingga penyerapan air/hara terganggu; tanaman kerdil, anakan sedikit, daun menua dini, sering disertai gejala kekurangan P. Pertumbuhan tidak merata dalam satu hamparan.",
 "pembeda":"Masalah berpusat di akar (pendek/rusak) pada tanah mineral masam (pH<4,5) — berbeda dari keracunan besi (gejala pada daun berupa bronzing) dan gangguan biotik (tidak ada patogen/serangga).",
 "penyebab":"Tanah mineral masam (ultisol/podzolik merah-kuning) yang mendominasi lahan tadah hujan Kalbar ber-pH rendah; pada pH<4,5 kelarutan Al3+ (dan Mn) melonjak dan meracuni ujung akar, sementara P terikat oleh Al/Fe.",
 "kondisi":"Tanah ultisol/podzolik ber-pH rendah, kejenuhan Al tinggi, kandungan bahan organik dan basa (Ca, Mg, K) rendah; diperberat oleh pengapuran yang belum memadai dan pemupukan tidak berimbang. Khas lahan tadah hujan Sekadau, Sintang, dan sekitarnya.",
 "dampak":"Akar rusak, serapan hara turun, pertumbuhan dan hasil merosot; memicu defisiensi P dan hara lain sekaligus.",
 "identifikasi":"Ukur pH tanah (umumnya 4-5); amati akar pendek menghitam dan pertumbuhan kerdil pada petak bertanah merah-kuning. Uji tanah bila memungkinkan.",
 "pht":["Ameliorasi: berikan kapur pertanian/dolomit sesuai pH dan kejenuhan Al (umumnya 1-2 ton/ha mengikuti uji tanah) untuk menaikkan pH dan menekan Al3+.",
  "Tambahkan bahan organik (kompos jerami, pupuk kandang) yang mengikat Al serta memperbaiki kesuburan dan daya simpan air.",
  "Tanam varietas adaptif tanah masam; berikan P (SP-36) untuk mengatasi pengikatan P oleh Al/Fe.",
  "Pemupukan berimbang N-P-K sesuai status hara; letakkan pupuk P dekat perakaran agar efisien."],
 "tip":"Pada tanah masam, menaikkan pH lebih dulu (kapur + bahan organik) membuat semua pupuk lain jauh lebih efektif — mengapur adalah investasi, bukan sekadar biaya."},
{"no":19,"nama":"Cekaman Kekeringan (Kekurangan Air)","latin":"Cekaman abiotik — defisit air","photo":None,"cap":None,"suggest":"Daun padi menggulung memanjang seperti bawang dan ujungnya mengering; tanah retak pecah-pecah di sela tanaman saat kemarau.",
 "gejala":"Daun menggulung memanjang ke arah tulang daun, layu pada siang hari, ujung/tepi daun mengering; pertumbuhan terhambat, pembungaan tertunda, dan malai hampa bila kekeringan terjadi saat bunting-berbunga. Tanah retak-retak.",
 "pembeda":"Daun menggulung dan tanah retak pada periode tanpa hujan; gejala paling parah di bagian petak yang paling kering, tanpa serangga/patogen — berbeda dari tungro (jingga+kerdil, fokus) dan keracunan besi (bronzing bintik oranye).",
 "penyebab":"Ketersediaan air tidak cukup karena hujan berhenti atau tidak turun; lahan tadah hujan sepenuhnya bergantung curah hujan tanpa irigasi cadangan.",
 "kondisi":"Musim kemarau atau jeda hujan panjang, tanah berdaya simpan air rendah (berpasir/porus), dan tanpa sumber irigasi. Paling merusak pada fase bunting-berbunga (fase paling peka terhadap air).",
 "dampak":"Anakan berkurang, malai hampa, pengisian gabah terganggu, dan hasil turun drastis; pada kekeringan berat tanaman mati/puso setempat.",
 "identifikasi":"Amati daun menggulung pada pagi/siang, tanah retak, dan warna daun memudar; catat fase tanaman saat kekeringan (kritis bila bunting-berbunga).",
 "pht":["Sesuaikan waktu tanam dengan awal musim hujan (kalender tanam) agar fase bunting-berbunga tidak jatuh pada puncak kemarau.",
  "Tanam varietas genjah dan toleran kekeringan (mis. Inpari 38/39/41 Tadah Hujan) agar cepat panen sebelum air habis.",
  "Perbaiki simpanan air: tambah bahan organik, kuatkan pematang, dan bangun embung/dam parit untuk memanen air hujan.",
  "Terapkan hemat air (mulsa jerami, tanam benih langsung/tabela) dan kendalikan gulma agar tidak bersaing air dengan padi."],
 "tip":"Di lahan tadah hujan, 'melawan kekeringan' dimulai dari kalender tanam dan varietas genjah — menanam tepat di awal hujan lebih menentukan daripada tindakan saat tanaman sudah kering."},
{"no":20,"nama":"Defisiensi Nitrogen (N)","latin":"Kekurangan N","photo":None,"cap":None,"suggest":"Tanaman pucat kekuningan merata, daun tua menguning lebih dulu, anakan sedikit, pertumbuhan lambat.",
 "gejala":"Seluruh tanaman hijau pucat sampai kekuningan merata; daun tua menguning lebih dulu (dari ujung ke pangkal), anakan sedikit, tanaman pendek dan lambat tumbuh.",
 "pembeda":"Menguning pucat merata mulai dari daun tua tanpa bercak/serangga — berbeda dari tungro (jingga + kerdil fokus), besi (bronzing bintik), dan K (nekrosis tepi daun tua).",
 "penyebab":"Ketersediaan N rendah atau serapan tidak cukup; N mudah tercuci oleh hujan deras di lahan tadah hujan.",
 "kondisi":"Lahan miskin hara (N rendah), pencucian N oleh hujan, waktu/dosis pemupukan tidak tepat, dan bahan organik mentah yang mengikat N sementara.",
 "dampak":"Anakan dan luas daun kurang sehingga potensi hasil rendah; tetapi kelebihan N juga berbahaya (memicu WBC, HDB, blas).",
 "identifikasi":"Gunakan Bagan Warna Daun (BWD) untuk menilai kebutuhan N secara objektif; amati warna pucat merata pada hamparan.",
 "pht":["Pemupukan N (urea) tepat dosis dan waktu berdasarkan Bagan Warna Daun (BWD), diberikan bertahap agar tidak tercuci.",
  "Perbaiki bahan organik dan efisiensi pupuk; hindari pemberian N berlebihan sekaligus.",
  "Sesuaikan dengan status lahan; berikan pupuk saat tanah lembap agar N tidak menguap/tercuci."],
 "tip":"Gunakan Bagan Warna Daun sebelum menambah urea. N cukup bukan berarti N banyak: kelebihan N justru mengundang wereng, HDB, dan blas."},
{"no":21,"nama":"Defisiensi Fosfor (P)","latin":"Kekurangan P (terikat Al/Fe)","photo":None,"cap":None,"suggest":"Tanaman kerdil, daun hijau tua kebiruan, anakan sedikit; tepi daun tua keunguan.",
 "gejala":"Tanaman kerdil dengan anakan sedikit; daun sempit, tegak, hijau tua kebiruan, kadang keunguan pada tepi/pangkal daun tua. Pematangan dan pengisian terlambat.",
 "pembeda":"Hijau tua-kebiruan dan anakan sangat sedikit (bukan menguning) — berbeda dari defisiensi N (menguning pucat). Umum di lahan tadah hujan masam karena P terikat Al/Fe.",
 "penyebab":"Ketersediaan P rendah karena diikat aluminium/besi menjadi Al-fosfat/Fe-fosfat pada tanah mineral masam (ultisol).",
 "kondisi":"Tanah ultisol/podzolik ber-pH rendah dengan Al/Fe tinggi; lahan tadah hujan yang memang miskin P.",
 "dampak":"Anakan dan malai sedikit sehingga potensi hasil rendah; tanaman lambat matang.",
 "identifikasi":"Amati kekerdilan + warna hijau tua kebiruan/keunguan pada hamparan; kaitkan dengan pH masam. Uji tanah bila memungkinkan.",
 "pht":["Berikan pupuk P (SP-36) sesuai status P tanah (rendah 100, sedang 75, tinggi 50 kg/ha — acuan PM-AAS).",
  "Naikkan pH dengan kapur/dolomit dan bahan organik agar P tidak terikat Al/Fe (meningkatkan ketersediaan P).",
  "Gunakan pupuk organik/kompos untuk memperbaiki efisiensi P; letakkan pupuk P dekat perakaran."],
 "tip":"Menambah P saja kurang efektif bila tanah sangat masam. Naikkan pH dulu (kapur + bahan organik) agar P yang diberikan tidak langsung terikat Al/Fe."},
{"no":22,"nama":"Defisiensi Kalium (K)","latin":"Kekurangan K","photo":None,"cap":None,"suggest":"Daun tua menguning-mengering dari ujung/tepi (nekrosis tepi), bercak coklat; batang lemah mudah rebah.",
 "gejala":"Daun tua menguning lalu mengering-coklat dari ujung dan tepi (nekrosis tepi); sering muncul bercak coklat (rentan bercak coklat), batang lemah dan mudah rebah.",
 "pembeda":"Gejala mulai dari daun tua/bawah pada tepi-ujung (bukan seluruh daun) dan tanaman rentan bercak coklat — berbeda dari N (menguning merata seluruh daun tua) dan besi (bronzing bintik oranye).",
 "penyebab":"Ketersediaan K rendah, umum pada tanah masam tadah hujan yang miskin basa (K, Ca, Mg).",
 "kondisi":"Tanah masam kejenuhan basa rendah, pengangkutan jerami keluar lahan (menguras K), dan pemupukan tidak berimbang.",
 "dampak":"Batang lemah, mudah rebah, gabah kurang berisi, dan meningkatnya penyakit bercak coklat; mutu dan hasil turun.",
 "identifikasi":"Amati nekrosis tepi/ujung daun tua + kecenderungan rebah dan bercak coklat pada hamparan; kaitkan dengan riwayat pengangkutan jerami.",
 "pht":["Pupuk K (KCl/NPK) sesuai anjuran; kembalikan jerami ke lahan (dikomposkan in situ) sebagai sumber K dan silika.",
  "Ameliorasi bahan organik dan kapur untuk menaikkan basa tanah.",
  "Pupuk silika untuk memperkuat batang (prinsip PM-AAS) dan mengurangi rebah serta serangan penyakit."],
 "tip":"Jerami padi kaya Kalium dan silika. Mengembalikan jerami (terkompos) ke lahan adalah pupuk K termurah untuk lahan tadah hujan."},
{"no":23,"nama":"Defisiensi Zink (Zn)","latin":"Kekurangan Zn","photo":None,"cap":None,"suggest":"Bercak/karat coklat pada daun tengah, pangkal daun memutih, tanaman kerdil dan terlambat 2-4 minggu setelah tanam.",
 "gejala":"Muncul 2-4 minggu setelah tanam: bercak/karat coklat pada daun tengah-bawah, pangkal daun memucat/memutih, daun mengecil, tanaman kerdil dan pertumbuhan tersendat (kadang disebut 'khaira').",
 "pembeda":"Karat coklat + pemutihan pangkal daun pada tanaman muda kerdil, sering berpetak (patchy) di area becek/berkapur — berbeda dari bercak coklat penyakit (bercak biji wijen menyebar) dan besi (bronzing dari ujung).",
 "penyebab":"Ketersediaan Zn rendah, diperberat oleh genangan, pH tinggi setempat (bekas kapur berlebih), dan bahan organik tinggi yang mengikat Zn.",
 "kondisi":"Tanah tergenang/becek terus-menerus, lahan baru, dan pengapuran berlebihan setempat.",
 "dampak":"Pertumbuhan terhambat pada fase awal; bila berat, tanaman mati atau hasil turun banyak.",
 "identifikasi":"Amati gejala 2-4 MST berupa karat coklat + pangkal daun memutih pada petak tertentu; respons cepat terhadap aplikasi Zn menguatkan diagnosis.",
 "pht":["Aplikasi pupuk Zn (ZnSO4) melalui tanah atau semprot daun; celup akar bibit dalam larutan/pasta Zn sebelum tanam.",
  "Perbaiki drainase agar tidak becek berkepanjangan untuk meningkatkan ketersediaan Zn.",
  "Gunakan varietas adaptif dan pupuk berimbang; hindari pengapuran berlebihan setempat."],
 "tip":"Defisiensi Zn muncul dini (2-4 MST) dan cepat pulih bila segera diberi Zn — kenali karat coklat + pangkal daun memutih agar tidak dikira penyakit."},
{"no":24,"nama":"Keracunan Besi (Fe)","latin":"Bronzing — Fe2+ berlebih","photo":None,"cap":None,"suggest":"Daun bawah bronzing: bintik coklat-oranye dari ujung daun pada petak rendah tergenang; akar berlapis film kemerahan.",
 "gejala":"Bintik-bintik kecil coklat-oranye pada daun bawah mulai dari ujung; pada berat seluruh daun kuning kemerahan sampai coklat (bronzing). Pertumbuhan terhambat, anakan sedikit, akar berselaput/berlapis kemerahan-hitam.",
 "pembeda":"Bronzing merata tanpa serangga dan tanpa pola fokus — berbeda dari WBC (ada serangga, hopperburn berkelompok) dan tungro (jingga + kerdil, pola fokus). Kunci: lihat film besi kemerahan di akar dan air.",
 "penyebab":"Pada tanah masam yang tergenang, besi berubah menjadi bentuk terlarut (Fe2+) yang bila berlebihan terserap akar dan meracuni jaringan tanaman.",
 "kondisi":"Terjadi pada petak tadah hujan dataran rendah/cekungan yang tergenang air hujan cukup lama dan bertanah masam; lebih jarang daripada di lahan pasang surut, tetapi bisa muncul di sawah tadah hujan rendah bukaan baru.",
 "dampak":"Menghambat pertumbuhan dan pengisian, menurunkan hasil; pada berat menyebabkan puso setempat.",
 "identifikasi":"Amati bronzing daun bawah + selaput besi di permukaan air/akar pada petak rendah; ukur pH tanah (biasanya masam). Bedakan dari penyakit dengan tidak adanya bercak patogen.",
 "pht":["Kelola air: keringkan petak secara berkala saat tergenang lama agar Fe2+ teroksidasi; perbaiki drainase petak cekungan.",
  "Ameliorasi kapur/dolomit dan bahan organik terkompos untuk menaikkan pH dan menekan Fe2+.",
  "Tanam varietas toleran; pemupukan berimbang (cukup P dan K) agar penyerapan Fe berlebih berkurang."],
 "tip":"Keracunan besi di tadah hujan muncul di petak rendah yang tergenang lama — pengeringan berkala dan perbaikan drainase biasanya cukup meredamnya."},
]

QID=[
("bug","Anakan muda mati, mudah dicabut, batang berlubang","Penggerek batang","Cari lubang & kotoran larva"),
("bug","Menguning 'terbakar' berkelompok + serangga coklat","Wereng batang coklat","Ketuk pangkal batang di air"),
("bug","Daun kuning-jingga dari ujung + tanaman kerdil (fokus)","Tungro (vektor wereng hijau)","Lihat pola fokus; cek wereng hijau"),
("bug","Bibit muda habis + telur merah muda di batang","Keong mas","Cari keong & telur merah muda"),
("bug","Batang terpotong menyerong, kerusakan dari dalam petak","Tikus sawah","Cari lubang aktif & jejak pematang"),
("bug","Batang terpotong di pangkal dekat tanah + ada liang","Orong-orong","Amati petak mengering, cari liang"),
("bug","Gabah hampa/bernoda saat masak susu + bau menyengat","Walang sangit","Ayun jaring pagi/sore"),
("bug","Daun tergulung, ada 'jendela' garis putih transparan","Hama putih palsu (pelipat daun)","Buka gulungan daun, cari larva"),
("bug","Anakan membentuk tabung 'pentil bawang' keputihan","Ganjur","Hitung anakan bertabung"),
("bug","Daun terkoyak/berlubang, daun habis dimakan","Belalang & ulat grayak","Periksa pangkal & tanah pagi hari"),
("bug","Bulir dimakan kawanan burung menjelang panen","Burung pipit","Amati jam 06-10 & 15-18"),
("microbe","Bercak abu-abu dari tepi daun; eksudat kuning pagi","Hawar daun bakteri (HDB)","Cari butiran bakteri kuning"),
("microbe","Bercak belah ketupat bermata (pusat putih, tepi coklat)","Blas daun","Periksa daun & leher malai"),
("microbe","Leher malai membusuk coklat, malai patah/hampa","Blas leher","Amati pangkal leher malai"),
("microbe","Bercak kecil oval 'biji wijen' merata di daun","Bercak coklat","Kaitkan status K, hara & air"),
("microbe","Bercak oval kelabu bertepi coklat di pelepah + sklerotia","Hawar pelepah","Buka kanopi dekat garis air"),
("microbe","Garis/bercak jingga pada helai daun (generatif)","Hawar daun jingga","Bedakan dari HDB lewat warna jingga"),
("water","Akar pendek/tumpul menghitam, kerdil, tanah masam merah-kuning","Keracunan Aluminium (Al)","Ukur pH tanah (4-5)"),
("water","Daun menggulung, tanah retak, malai hampa saat kemarau","Cekaman kekeringan","Catat fase tanaman & curah hujan"),
("water","Tanaman pucat kekuningan merata mulai daun tua","Defisiensi Nitrogen (N)","Gunakan Bagan Warna Daun (BWD)"),
("water","Kerdil, daun hijau tua kebiruan/keunguan, anakan sedikit","Defisiensi Fosfor (P)","Kaitkan pH masam; uji tanah"),
("water","Daun tua menguning-coklat dari tepi/ujung, mudah rebah","Defisiensi Kalium (K)","Cek riwayat jerami diangkut"),
("water","Karat coklat + pangkal daun memutih, kerdil 2-4 MST","Defisiensi Zink (Zn)","Uji respons aplikasi ZnSO4"),
("water","Daun bawah bronzing bintik oranye pada petak rendah tergenang","Keracunan besi (Fe)","Ukur pH; lihat film besi di air"),
]

REFS=[
"Badan Perakitan dan Modernisasi Pertanian (BRMP), Kementerian Pertanian. 2026. Buku Saku PM-AAS (Pertanian Modern - Advanced Agricultural System). Jakarta.",
"Balai Besar Penelitian Tanaman Padi (BB Padi), Badan Litbang Pertanian. Varietas Unggul Baru Padi Inpari 38, 39, 41 Tadah Hujan Agritan untuk Lahan Sawah Tadah Hujan. Kementerian Pertanian.",
"Wijayanto, B., Kiswanto, dan G.O. Manurung. 2013. Hama dan Penyakit Utama Tanaman Padi. BPTP Lampung, Badan Litbang Pertanian, Kementerian Pertanian.",
"Jumadi, O. dan H. Karim (Ed.). Organisme Pengganggu Tanaman (OPT) dan Agens Hayati (AH) pada Tanaman Padi. Jurusan Biologi FMIPA Universitas Negeri Makassar.",
"Farizi, dkk. Evaluasi Kesesuaian Lahan Sawah Tadah Hujan untuk Tanaman Padi di Kecamatan Bonti, Kabupaten Sanggau, Kalimantan Barat. Pedontropika: Jurnal Ilmu Tanah dan Sumber Daya Lahan, Universitas Tanjungpura.",
"Balai Penelitian Tanah, Badan Litbang Pertanian. Pengelolaan Tanah Masam (Ultisol/Podzolik): Pengapuran, Bahan Organik, dan Pemupukan Berimbang. Kementerian Pertanian.",
"Direktorat Perlindungan Tanaman Pangan, Kementerian Pertanian. Pedoman Pengamatan dan Pengendalian OPT Padi (ambang pengendalian).",
"Puslitbang Tanaman Pangan. Masalah Lapang Hama, Penyakit, dan Hara pada Padi. Badan Litbang Pertanian, Kementerian Pertanian.",
"International Rice Research Institute (IRRI). Rice Knowledge Bank - Pests, Diseases and Nutrient Disorders of Rice.",
]

TIPS=[
"Bawa buku saku ini, kaca pembesar (loupe), kantong plastik/botol contoh, dan alat ukur pH tanah sederhana saat pengamatan.",
"Amati minimal 10 titik secara zig-zag per petak, sekali seminggu; catat jenis, jumlah, dan luas serangan sebelum memutuskan tindakan.",
"Bedakan dulu: gangguan hidup (hama/penyakit) atau tidak hidup (hara/air)? Gangguan hara/air biasanya merata satu hamparan tanpa serangga/patogen dan mengikuti pola tanah/kelembapan.",
"Di lahan tadah hujan, sesuaikan waktu tanam dengan awal musim hujan dan pilih varietas genjah agar fase berbunga tidak jatuh saat kekeringan.",
"Pada tanah masam (ultisol/podzolik), naikkan pH dengan kapur/dolomit + bahan organik sebelum menambah pupuk lain agar pupuk tidak terbuang.",
"Kembalikan jerami (dikomposkan in situ) ke lahan sebagai sumber Kalium dan silika — memperkuat batang dan menekan bercak coklat serta HDB.",
"Gunakan Bagan Warna Daun (BWD) untuk menakar N; kelebihan N mengundang wereng coklat, HDB, dan blas.",
"Utamakan tanam serempak satu hamparan — kunci menekan penggerek, tungro, tikus, dan burung sekaligus.",
"Pestisida adalah pilihan terakhir: patuhi ambang, prinsip 6 tepat (jenis, dosis, waktu, cara, sasaran, lokasi), rotasi bahan aktif, dan gunakan APD.",
"Lindungi musuh alami (laba-laba, kepik, parasitoid, burung hantu) — mereka bekerja gratis sepanjang musim bila tidak dibunuh insektisida.",
]

VARIETAS="Pemilihan varietas adalah komponen PHT paling awal dan murah. Untuk lahan tadah hujan, utamakan varietas berumur genjah dan toleran kekeringan agar cepat panen sebelum air habis, serta tahan penyakit utama (blas dan HDB). Kementerian Pertanian melepas varietas khusus tadah hujan: Inpari 38, 39, dan 41 Tadah Hujan Agritan (genjah, agak toleran kekeringan; Inpari 39 tahan 4 ras blas) serta Inpari 46 GSR Tadah Hujan. Acuan PM-AAS 2026 juga merekomendasikan Padjadjaran, Inpari 42 GSR, dan Cakrabuana Agritan (genjah, tahan rebah) untuk sawah dan tadah hujan, Inpari 32 HDB (tahan hawar daun bakteri), serta Inpago 12 Agritan untuk kondisi gogo/kering. Sesuaikan pilihan dengan curah hujan, tingkat kemasaman tanah, dan status hara setempat."
